dist: focal
sudo: false
language: cpp
cache: ccache

addons:
  apt:
    packages: ninja-build libboost-dev libboost-system-dev libboost-thread-dev libboost-chrono-dev

script:
  - git log -1
  - mkdir -p travis-build
  - cd travis-build
  - ccache -s
  - cmake .. -G Ninja -DCMAKE_CXX_FLAGS="-Werror -Wall"
  - cmake --build . -- -k 100
  - ctest .
  - ccache -s
